import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Container, Flex, Section, Theme } from '@radix-ui/themes';
import { Sidebar } from '@/components/sidebar';
import '@radix-ui/themes/styles.css';
import Header from '@/components/header';
import { SidebarProvider } from '@/contexts/sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ margin: 0 }}>
        <Theme radius="medium" appearance="dark">
          <Flex direction="column" height="100vh">
            <Header />
            <SidebarProvider>
              <Flex direction="row" flexGrow="1" minHeight="0">
                <Sidebar />
                <div
                  style={{
                    overflow: 'auto',
                    background: 'var(--gray-2)',
                    width: '100%',
                    padding: '20px',
                  }}
                >
                  {children}
                </div>
              </Flex>
            </SidebarProvider>
          </Flex>
        </Theme>
      </body>
    </html>
  );
}
