import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { SiteHeader } from '@/components/sidebar/site-header';
import AppSidebar from '@/components/sidebar/app-sidebar';
import { Toaster } from '@/components/ui/sonner';
import { AlertCircle, CheckCircle, XCircle } from 'lucide-react';
import QueryProvider from '@/components/providers/query-client-provider';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <SidebarProvider
              defaultOpen={true}
              style={
                {
                  '--sidebar-width': 'calc(var(--spacing) * 72)',
                  '--header-height': 'calc(var(--spacing) * 12)',
                } as React.CSSProperties
              }
            >
              <AppSidebar variant="inset" />
              <SidebarInset>
                <SiteHeader />
                <div className="flex-1 flex flex-col">{children}</div>
                <Toaster
                  closeButton
                  position="top-right"
                  richColors
                  swipeDirections={['right', 'top']}
                  icons={{
                    success: (
                      <CheckCircle className="h-5 w-5 fill-green-600 text-white outline-none" />
                    ),
                    error: (
                      <AlertCircle className="h-5 w-5 fill-red-600 text-white outline-none" />
                    ),
                    warning: (
                      <AlertCircle className="h-5 w-5 fill-yellow-600 text-white outline-none" />
                    ),
                    info: (
                      <AlertCircle className="h-5 w-5 fill-blue-600 text-white outline-none" />
                    ),
                    close: (
                      <XCircle className="h-5 w-5 fill-gray-600 text-white outline-none" />
                    ),
                  }}
                />
              </SidebarInset>
            </SidebarProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
